apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-portfolio
  namespace: go-app
  labels:
    role: go-portfolio
    env: dev
spec: 
  replicas: 1
  selector: 
    matchLabels:
      role: go-portfolio
  template: 
    metadata: 
      labels: 
        role: go-portfolio
    spec:
      containers: 
      - name: go-portfolio
        image: avian19/go-port:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports: 
        - containerPort: 8080
