apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-portfolio
  namespace: go-app
  labels:
    role: go-portfolio
    env: dev
spec:
  replicas: {{ .Values.replicaCount }}  # Use replica count from values.yaml
  selector:
    matchLabels:
      role: go-portfolio
  template:
    metadata:
      labels:
        role: go-portfolio
    spec:
      containers:
      - name: go-portfolio
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # Pull image and tag from values.yaml
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"

